### PR TITLE
handles space-separated list of hostname

### LINKED ISSUE #10: space-separated list of hostnames doesn't work anymore
Hi,

I upgraded Prosody to 0.11 and to Lua 5.2. With mod_auth_ldap users can authenticate, but only if the option `ldap_server` consists of a single hostname or IP. A space-separated list of hostnames/IPs doesn't work anymore with lua-ldap 1.2.5 
Using a space-separated list of e.g. three hostnames leads to the following log entries when a user tries to authenticate:
```
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	error 	LDAP: LuaLDAP: Error connecting to server
Jan 15 01:19:15 c2s55e97c749000	info	Failed authentication attempt (not-authorized) for user xxxx from IP: xxx.xxx.xxx.xxx
```

When using the current version in master, the error message changes to:

```
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap error   LDAP: Bad parameter to an ldap routine
```

Kind wishes,
Dan

### PR DESCRIPTION
**Pull request by fperrad**
fix #10

### CODE REVIEW

File: src/lualdap.c [hunk 1]
```diff
@@ -981,8 +981,12 @@ static int lualdap_open_simple (lua_State *L) {
 	if (strstr(host, "://") != NULL) {
 		err = ldap_initialize(&conn->ld, host);
 	} else {
-		const char *host_with_schema = lua_pushfstring(L, "ldap://%s", host);
-		err = ldap_initialize(&conn->ld, host_with_schema);
+		lua_getfield (L, 1, "gsub");
```
Comment (devurandom) [inline src/lualdap.c:984]: Why do you call `gsub` on the argument, instead of `luaL_gsub`? I would think the latter is guaranteed to give you the results you expect, while the former could be modified by the user?

File: src/lualdap.c [hunk 2]
```diff
@@ -981,8 +981,12 @@ static int lualdap_open_simple (lua_State *L) {
...
+		lua_pushvalue (L, 1); /* host */
+		lua_pushstring (L, "(%S+)");
+		lua_pushstring (L, "ldap://%1");
+		lua_call (L, 3, 1); /* host:gsub('(%S+)', 'ldap://%1') */
+		err = ldap_initialize(&conn->ld, lua_tostring (L, -1));
```
Comment (devurandom) [inline src/lualdap.c:989]: I would add a comment that `ldap_initialize` handles comma and whitespace separated hostnames itself (i.e. we do not need to do anything on our side to make this work).

**Review by devurandom — COMMENTED** [review]
Looks fine, but I would add a comment to the call to `ldap_initialize` and think about whether `host:gsub` or `luaL_gsub` should be called.

File: src/lualdap.c (hunk 2 above)
Comment (fperrad) [reply src/lualdap.c:989]: Ok

File: src/lualdap.c (hunk 1 above)
Comment (fperrad) [reply src/lualdap.c:984]: `luaL_gsub` doesn't handle the *regex* stuff like *class character* and *capture*.
see https://github.com/lua/lua/blob/master/lauxlib.c#L975-L995
`luaL_gsub` does only string substitution.

Now, I retrieve the method `:gsub`, but I could use the function `string.gsub` instead.

Comment (devurandom) [reply src/lualdap.c:984]: I would prefer that, if I was to write this code. That makes it easier for you to know what you have available and weird changes a user makes cannot throw a wrench into your gears. But what is the consensus of the Lua community on this?

File: src/lualdap.c [hunk 3]
```diff
@@ -981,9 +981,15 @@ static int lualdap_open_simple (lua_State *L) {
 	if (strstr(host, "://") != NULL) {
 		err = ldap_initialize(&conn->ld, host);
 	} else {
-		const char *host_with_schema = lua_pushfstring(L, "ldap://%s", host);
-		err = ldap_initialize(&conn->ld, host_with_schema);
-		lua_pop(L, 1);
+		lua_getglobal (L, "string");
```
Comment (devurandom) [inline src/lualdap.c:984]: Should the string library be loaded from C instead of relying on a global being present?

```suggestion
		luaL_requiref (LUA_STRLIBNAME, luaopen_string);
```

**Review by devurandom — APPROVED** [review]
Assuming you agree with my suggestion to use `luaL_requiref`: LGTM

File: src/lualdap.c (hunk 3 above)
Comment (fperrad) [reply src/lualdap.c:984]: If an user remove the standard library `string`,
I don't think that the (silency) reload of this library is a good idea.

I prefer to protect the lualdap code, like this :
```
	lua_getglobal (L, "string");
	lua_getfield (L, -1, "gsub");
	if (!lua_isfunction (L, -1))
		return faildirect (L, LUALDAP_PREFIX"string.gsub broken");
```

Comment (devurandom) [reply src/lualdap.c:984]: I think the protection is not necessary. `lua_call` will fail in that case, hopefully with some useful error message. (Except that we will not know which function we tried to call. But it should tell us that what we tried to call was not a function.)

-> LGTM

Comment (devurandom) [reply src/lualdap.c:984]: > If an user remove the standard library `string`,
> I don't think that the (silency) reload of this library is a good idea.

Think of cases where you are not running a Lua interpreter, but where Lua is embedded into another application. The application programmer might not have exposed some (or any) libraries to the Lua scripts.

Comment (fperrad) [reply src/lualdap.c:984]: With the protection that I suggest, an embedded will know that `lualdap` depends on `string.gsub`.

The default message tell that you try to call something which is not a function, so it is not easy to find the real problem.
